# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: member.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "MemberRequest" do
    optional :id, :int64, 1
  end
  add_message "MemberReply" do
    optional :name, :string, 1
    optional :email, :string, 2
  end
  add_message "OrderReply" do
    optional :number, :string, 1
  end
end

MemberRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("MemberRequest").msgclass
MemberReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("MemberReply").msgclass
OrderReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("OrderReply").msgclass
